FROM node:20-alpine AS builder

WORKDIR /app

COPY ./package.json ./package.json

RUN npm install

COPY . .

RUN npx prisma generate

RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 8000

CMD ["node","dist/index.js"]
