FROM node:20-alpine AS builder

WORKDIR /app

COPY ./package.json ./package.json

RUN npm install

COPY . .

RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 8081

CMD ["node","public/index.js"]
